
name: PythonCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter: 
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        run: pip install poetry
      - name: install dependency
        run: make install  
      - name: lint
        run: make lint
      - name: code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{}}
        with:
          coverageCommand: make coverage